# Generated by Django 5.1.4 on 2024-12-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='recipe_img', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='describe',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование блюда'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.TextField(verbose_name='Способ приготовления'),
        ),
    ]
