# Generated by Django 5.1.4 on 2024-12-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipe_options_recipe_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image1',
            field=models.URLField(blank=True, verbose_name='Дополнительное изображение'),
        ),
    ]
